version: 2.1

orbs:
  docker: circleci/docker@1.7.0
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: flauberjp
          password: $DOCKER_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker build -t flauberjp/udagram-frontend:<< pipeline.number >> -t flauberjp/udagram-frontend:latest .
          echo $DOCKER_PASSWORD | docker login -u flauberjp --password-stdin
          docker push flauberjp/udagram-frontend --all-tags
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: MyEKSCluster
          install-kubectl: true

workflows:
  my-workflow:
    jobs:
      - my-job
      - aws-eks/update-container-image:
          cluster-name: MyEKSCluster
          resource-name: deployment/frontend
          container-image-updates: "frontend=flauberjp/udagram-frontend:<< pipeline.number >>"
          requires:
            - my-job
